name: graphormer
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pip<24.1
    - numpy<1.20
    - cython
    - torch==2.2.0+cu121
    - torchvision
    - torchaudio
    - lmdb
    - tensorboardX==2.4.1
    - ogb==1.3.2
    - rdkit
    - omegaconf==2.0.0
    - hydra-core>=1.0.7,<1.1
    - regex
    - sacrebleu>=1.4.12
    - bitarray
    - cffi
    - tqdm
  - pytorch::pytorch=2.2.0
  - pytorch::torchvision
  - pytorch::torchaudio

